name: HacroStaff
version: 1.1
main: fr.acilaw.hacrostaff.Main
author: Acilaw
commands:
  staff:
    description: inventaire staff pour les modérateurs
  randomTeleportPlayer:
    description: permet de se tp à un joueur aléatoire
