name: HacroStaff
version: 1.0
main: fr.acilaw.hacrostaff.HacroStaff
author: Acilaw
commands:
  staff:
    description: inventaire staff pour les modérateurs
  randomTeleportPlayer:
    description: permet de se tp à un joueur aléatoire
  freeze:
    description: freeze un joueur
  punish:
    description: ouvre un menu permettant de faire certaines actions sur un joueur.
  cps:
    description: compte le cps d'un joueur