name: HacroSkript
version: 1.0
main: fr.acilaw.hacroskript.Main
author: Acilaw
commands:
  gambling:
    description: Envoie le message du pnj gambling
  poubelle:
    description: Redirige la commande vers trash
  pt:
    description: Redirige la commande vers playtime
